### ISSUE TITLE
256 bits instead of 256 bytes

### ISSUE THREAD

**Issue by gallen** [androlo/solidity-workshop#3]
Doesn't the 'bytes' mean 'bits' in the context actually?

Advanced Solidity V - Solidity value-types
 
uint, int, boolean
> When dealing with numbers that are less than 256 **bytes** in size, there will be some conversions taking place.

**Comment by androlo** [comment]
Sorry for late reply.

Yes you are correct. I am going to add a note that this is old docs that are no longer up to date, so I will not be editing the text. Sorry for not adding this note sooner.
